# Generated by Django 4.1 on 2023-10-14 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='slug_url',
            new_name='slug',
        ),
    ]
